version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: famille_app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    labels:
      # Enable Traefik
      - "traefik.enable=true"

      # HTTPS Router
      - "traefik.http.routers.famille_app.rule=Host(`famille.matheo-olsen.fr`)"
      - "traefik.http.routers.famille_app.entrypoints=websecure"
      - "traefik.http.routers.famille_app.tls.certresolver=myresolver"

      # HTTP to HTTPS Redirection
      - "traefik.http.routers.famille_app-http.rule=Host(`famille.matheo-olsen.fr`)"
      - "traefik.http.routers.famille_app-http.entrypoints=web"
      - "traefik.http.routers.famille_app-http.middlewares=redirect-https"
      - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"

      # Traefik Network
      - "traefik.docker.network=famille_public_network"

      # Application Port
      - "traefik.http.services.famille_app.loadbalancer.server.port=3000"
    networks:
      - famille_internal_network
      - famille_public_network
    ports:
      - "3000:3000" # Uncomment this for local dev
    expose:
      - "3000"

  db:
    image: postgres:15
    container_name: famille_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - famille_db_data:/var/lib/postgresql/data
    networks:
      - famille_internal_network
    ports:
      - "5432:5432" # Uncomment this for local dev
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4
    container_name: famille_adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - famille_internal_network
    ports:
      - "8080:8080" # Adminer available at localhost:8080 for debugging

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=devneosianexus@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--log.level=ERROR"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - famille_public_network

volumes:
  famille_db_data:
  famille_app_data:

networks:
  famille_public_network:
    driver: bridge
    name: famille_public_network
  famille_internal_network:
    driver: bridge
    name: famille_internal_network
