services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: famille_app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - famille_app_data:/app
    networks:
      - famille_internal_network
      - famille_public_network

  db:
    image: postgres:15
    container_name: famille_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - famille_db_data:/var/lib/postgresql/data
    networks:
      - famille_internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  famille_db_data:
  famille_app_data:

networks:
  famille_public_network:
    driver: bridge
    name: famille_public_network
  famille_internal_network:
    driver: bridge
    name: famille_internal_network
